### ISSUE TITLE
Filtering by language

### ISSUE THREAD

**Issue by imax9000** [bluesky-social/jetstream-legacy#15]
I took a stab at adding filtering by post language (in addition to DID and collection) and it turned out to be not as straightforward as I hoped. DID and collection are present in the metadata, so matching them doesn't require parsing the record. But language is both collection-specific and is only indicated inside the record.

Any advice on whether the added runtime cost would be acceptable, and if yes - how to  best approach the implementation side?

**Comment by jazware** [comment]
The idea behind Jetstream is to completely avoid unpacking the records themselves into lexicon types so I don't think that kind of filtering is a great fit. I think of Jetstream as a Layer 1.5 firehose compared the the Layer 1 firehose of the repo sync firehose, but it's not quite a Layer 2 firehose (i.e. Application-layer). I think a Layer 2 firehose would be a better place to do filtering based on the contents of records themselves and not just the metadata of the repo op. Ideally this would be a service provided by an AppView directly or at least alongside an AppView and could include additional context i.e. User A unfollowed User B instead of User A deleted the follow with rkey ASDF.
